<a href="https://colab.research.google.com/github/HarikaSatti06112001/CMPE255_Assisgnment4/blob/main/cmpe255_a4_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder

In [2]:
from google.colab import files
uploaded = files.upload()

Saving heart.csv to heart.csv

In [3]:
df = pd.read_csv('/content/heart.csv')

In [4]:
df.shape

(1025, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [6]:
df.head().T

              0      1      2      3      4
age        52.0   53.0   70.0   61.0   62.0
sex         1.0    1.0    1.0    1.0    0.0
cp          0.0    0.0    0.0    0.0    0.0
trestbps  125.0  140.0  145.0  148.0  138.0
chol      212.0  203.0  174.0  203.0  294.0
fbs         0.0    1.0    0.0    0.0    1.0
restecg     1.0    0.0    1.0    1.0    1.0
thalach   168.0  155.0  125.0  161.0  106.0
exang       0.0    1.0    1.0    0.0    0.0
oldpeak     1.0    3.1    2.6    0.0    1.9
slope       2.0    0.0    0.0    2.0    1.0
ca          2.0    0.0    0.0    1.0    3.0
thal        3.0    3.0    3.0    3.0    2.0
target      0.0    0.0    0.0    0.0    0.0

In [7]:
!pip install impyute

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting impyute
  Downloading impyute-0.0.8-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from impyute) (1.7.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from impyute) (1.0.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from impyute) (1.21.6)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->impyute) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->impyute) (3.1.0)
Installing collected packages: impyute
Successfully installed impyute-0.0.8

In [8]:
df['trestbps'] = pd.to_numeric(df['trestbps'], errors='coerce')
df['thal'] = pd.to_numeric(df['thal'], errors='coerce')
df['oldpeak'] = pd.to_numeric(df['oldpeak'], errors='coerce')

In [9]:
df.isnull().sum().sort_values(ascending=False)

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [17]:
numerical_features = []
categorical_features = []

for i in df.drop('oldpeak', axis=1).columns:
    if df[i].nunique()>7:
        numerical_features.append(i)
    else:
        categorical_features.append(i)
to_encode = [feat for feat in categorical_features if df[feat].dtype=='object']
to_encode
ode = OrdinalEncoder(dtype = int)
def encode(data):
    '''function to encode non-nan data and replace it in the original data'''
   
    nonulls = np.array(data.dropna())
    
    impute_reshape = nonulls.reshape(-1,1)
   
    impute_ordinal = ode.fit_transform(impute_reshape)
   
    data.loc[data.notnull()] = np.squeeze(impute_ordinal)
    return data

#create a for loop to iterate through each column in the data
for columns in to_encode:
    encode(df[columns])

In [18]:
df.loc[:, categorical_features].head(10)

   sex  cp  fbs  restecg  exang  slope  ca  thal  target
0    1   0    0        1      0      2   2     3       0
1    1   0    1        0      1      0   0     3       0
2    1   0    0        1      1      0   0     3       0
3    1   0    0        1      0      2   1     3       0
4    0   0    1        1      0      1   3     2       0
5    0   0    0        0      0      1   0     2       1
6    1   0    0        2      0      0   3     1       0
7    1   0    0        0      1      1   1     3       0
8    1   0    0        0      0      2   0     3       0
9    1   0    0        0      1      1   2     2       0

In [19]:
X = df.drop('oldpeak', axis=1)

In [20]:
X_train = X.loc[:300,]
X_test = X.loc[300:,]

In [21]:
from impyute.imputation.cs import mice

In [23]:
X_train_numerical = X_train.loc[:,numerical_features].astype('float64')
X_train.loc[:,numerical_features].isna().sum().sort_values(ascending=False)

age         0
trestbps    0
chol        0
thalach     0
dtype: int64

In [26]:
X_train.loc[:,numerical_features].isna().sum().sort_values(ascending=False)

age         0
trestbps    0
chol        0
thalach     0
dtype: int64

In [27]:
!pip install fancyimpute  
from fancyimpute import KNN

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting fancyimpute
  Downloading fancyimpute-0.7.0.tar.gz (25 kB)
Collecting knnimpute>=0.1.0
  Downloading knnimpute-0.1.0.tar.gz (8.3 kB)
Requirement already satisfied: scikit-learn>=0.24.2 in /usr/local/lib/python3.7/dist-packages (from fancyimpute) (1.0.2)
Requirement already satisfied: cvxpy in /usr/local/lib/python3.7/dist-packages (from fancyimpute) (1.2.1)
Requirement already satisfied: cvxopt in /usr/local/lib/python3.7/dist-packages (from fancyimpute) (1.3.0)
Requirement already satisfied: pytest in /usr/local/lib/python3.7/dist-packages (from fancyimpute) (3.6.4)
Collecting nose
  Downloading nose-1.3.7-py3-none-any.whl (154 kB)
     |████████████████████████████████| 154 kB 38.6 MB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from knnimpute>=0.1.0->fancyimpute) (1.15.0)
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.7/dist-packages (from knnimpute>=0.1.0->fancyimpute) (1.21.6)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (1.7.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (1.2.0)
Requirement already satisfied: osqp>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from cvxpy->fancyimpute) (0.6.2.post0)
Requirement already satisfied: scs>=1.1.6 in /usr/local/lib/python3.7/dist-packages (from cvxpy->fancyimpute) (3.2.0)
Requirement already satisfied: ecos>=2 in /usr/local/lib/python3.7/dist-packages (from cvxpy->fancyimpute) (2.0.10)
Requirement already satisfied: qdldl in /usr/local/lib/python3.7/dist-packages (from osqp>=0.4.1->cvxpy->fancyimpute) (0.1.5.post2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from pytest->fancyimpute) (57.4.0)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest->fancyimpute) (1.4.1)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest->fancyimpute) (1.11.0)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest->fancyimpute) (9.0.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.7/dist-packages (from pytest->fancyimpute) (0.7.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from pytest->fancyimpute) (22.1.0)
Building wheels for collected packages: fancyimpute, knnimpute
  Building wheel for fancyimpute (setup.py) ... done
  Created wheel for fancyimpute: filename=fancyimpute-0.7.0-py3-none-any.whl size=29899 sha256=97781e1836715e21f4013313af9291d079ffd67941a3d00c99f60bc94189df03
  Stored in directory: /root/.cache/pip/wheels/e3/04/06/a1a7d89ef4e631ce6268ea2d8cde04f7290651c1ff1025ce68
  Building wheel for knnimpute (setup.py) ... done
  Created wheel for knnimpute: filename=knnimpute-0.1.0-py3-none-any.whl size=11353 sha256=c16f8b8f00286c00c3c385e89c13c06319f141c27908c346974b433f63b68c93
  Stored in directory: /root/.cache/pip/wheels/72/21/a8/a045cacd9838abd5643f6bfa852c0796a99d6b1494760494e0
Successfully built fancyimpute knnimpute
Installing collected packages: nose, knnimpute, fancyimpute
Successfully installed fancyimpute-0.7.0 knnimpute-0.1.0 nose-1.3.7

In [28]:
KNN_imputer = KNN()

In [29]:
X_train_imputed = pd.DataFrame(np.round(KNN_imputer.fit_transform(X_train)),columns = X_train.columns)

Imputing row 1/301 with 0 missing, elapsed time: 0.024
Imputing row 101/301 with 0 missing, elapsed time: 0.024
Imputing row 201/301 with 0 missing, elapsed time: 0.024
Imputing row 301/301 with 0 missing, elapsed time: 0.025

/usr/local/lib/python3.7/dist-packages/fancyimpute/solver.py:55: UserWarning: Input matrix is not missing any values
  warnings.warn("Input matrix is not missing any values")

In [30]:
X_train_imputed.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [31]:
X_train_imputed.describe().T

          count        mean        std    min    25%    50%    75%    max
age       301.0   53.401993   9.488653   29.0   46.0   54.0   60.0   77.0
sex       301.0    0.734219   0.442484    0.0    0.0    1.0    1.0    1.0
cp        301.0    0.950166   1.013661    0.0    0.0    1.0    2.0    3.0
trestbps  301.0  131.803987  18.395057   94.0  120.0  130.0  140.0  200.0
chol      301.0  247.196013  56.871535  126.0  208.0  240.0  283.0  564.0
fbs       301.0    0.166113   0.372802    0.0    0.0    0.0    0.0    1.0
restecg   301.0    0.495017   0.526759    0.0    0.0    0.0    1.0    2.0
thalach   301.0  150.973422  23.422908   71.0  138.0  154.0  169.0  202.0
exang     301.0    0.342193   0.475234    0.0    0.0    0.0    1.0    1.0
slope     301.0    1.425249   0.631316    0.0    1.0    2.0    2.0    2.0
ca        301.0    0.697674   1.009106    0.0    0.0    0.0    1.0    4.0
thal      301.0    2.315615   0.597262    0.0    2.0    2.0    3.0    3.0
target    301.0    0.531561   0.499834    0.0    0.0    1.0    1.0    1.0

In [32]:
X_train_imputed.describe().T

          count        mean        std    min    25%    50%    75%    max
age       301.0   53.401993   9.488653   29.0   46.0   54.0   60.0   77.0
sex       301.0    0.734219   0.442484    0.0    0.0    1.0    1.0    1.0
cp        301.0    0.950166   1.013661    0.0    0.0    1.0    2.0    3.0
trestbps  301.0  131.803987  18.395057   94.0  120.0  130.0  140.0  200.0
chol      301.0  247.196013  56.871535  126.0  208.0  240.0  283.0  564.0
fbs       301.0    0.166113   0.372802    0.0    0.0    0.0    0.0    1.0
restecg   301.0    0.495017   0.526759    0.0    0.0    0.0    1.0    2.0
thalach   301.0  150.973422  23.422908   71.0  138.0  154.0  169.0  202.0
exang     301.0    0.342193   0.475234    0.0    0.0    0.0    1.0    1.0
slope     301.0    1.425249   0.631316    0.0    1.0    2.0    2.0    2.0
ca        301.0    0.697674   1.009106    0.0    0.0    0.0    1.0    4.0
thal      301.0    2.315615   0.597262    0.0    2.0    2.0    3.0    3.0
target    301.0    0.531561   0.499834    0.0    0.0    1.0    1.0    1.0

In [33]:
from sklearn.preprocessing import MinMaxScaler

In [34]:
scaler = MinMaxScaler()
scaler.fit(X_train_imputed)
X_train_scaled = scaler.transform(X_train_imputed)

In [35]:
X_train_scaled = pd.DataFrame(data=X_train_scaled, columns = X_train.columns)
X_train_scaled.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,slope,ca,thal,target
count,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000,301.000000
mean,0.508375,0.734219,0.316722,0.356641,0.276703,0.166113,0.247508,0.610484,0.342193,0.712625,0.174419,0.771872,0.531561
std,0.197680,0.442484,0.337887,0.173538,0.129844,0.372802,0.263380,0.178801,0.475234,0.315658,0.252276,0.199087,0.499834
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.354167,0.000000,0.000000,0.245283,0.187215,0.000000,0.000000,0.511450,0.000000,0.500000,0.000000,0.666667,0.000000
50%,0.520833,1.000000,0.333333,0.339623,0.260274,0.000000,0.000000,0.633588,0.000000,1.000000,0.000000,0.666667,1.000000
75%,0.645833,1.000000,0.666667,0.433962,0.358447,0.000000,0.500000,0.748092,1.000000,1.000000,0.250000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [36]:
X_test_numerical = X_test.loc[:,numerical_features].astype('float64')

In [38]:
X_test_imputed = pd.DataFrame(np.round(KNN_imputer.fit_transform(X_test)),columns = X_test.columns)

/usr/local/lib/python3.7/dist-packages/fancyimpute/solver.py:55: UserWarning: Input matrix is not missing any values
  warnings.warn("Input matrix is not missing any values")

Imputing row 1/725 with 0 missing, elapsed time: 0.206
Imputing row 101/725 with 0 missing, elapsed time: 0.207
Imputing row 201/725 with 0 missing, elapsed time: 0.207
Imputing row 301/725 with 0 missing, elapsed time: 0.207
Imputing row 401/725 with 0 missing, elapsed time: 0.208
Imputing row 501/725 with 0 missing, elapsed time: 0.208
Imputing row 601/725 with 0 missing, elapsed time: 0.208
Imputing row 701/725 with 0 missing, elapsed time: 0.208

In [39]:
X_test_imputed = pd.DataFrame(np.round(KNN_imputer.fit_transform(X_test)),columns = X_test.columns)

Imputing row 1/725 with 0 missing, elapsed time: 0.110
Imputing row 101/725 with 0 missing, elapsed time: 0.111
Imputing row 201/725 with 0 missing, elapsed time: 0.112
Imputing row 301/725 with 0 missing, elapsed time: 0.112
Imputing row 401/725 with 0 missing, elapsed time: 0.112
Imputing row 501/725 with 0 missing, elapsed time: 0.113
Imputing row 601/725 with 0 missing, elapsed time: 0.113
Imputing row 701/725 with 0 missing, elapsed time: 0.113

/usr/local/lib/python3.7/dist-packages/fancyimpute/solver.py:55: UserWarning: Input matrix is not missing any values
  warnings.warn("Input matrix is not missing any values")