<a href="https://colab.research.google.com/github/HarikaSatti06112001/CMPE255_Assisgnment4/blob/main/cmpe255_Assignment4_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df = pd.read_csv('/content/IRIS.csv')
df.dropna(axis=1,inplace=True)
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [5]:
df['petal_width'] = df['petal_width']/df['petal_width'].max()
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4         0.08  Iris-setosa
1           4.9          3.0           1.4         0.08  Iris-setosa
2           4.7          3.2           1.3         0.08  Iris-setosa
3           4.6          3.1           1.5         0.08  Iris-setosa
4           5.0          3.6           1.4         0.08  Iris-setosa

In [6]:
df['petal_length'] = (df['petal_length'] - df['petal_length'].min())/(df['petal_length'].max() - df['petal_length'].min())

In [7]:
df['sepal_length'] = (df['sepal_length']-df['sepal_length'].mean())/df['sepal_length'].std()

In [8]:
df['sepal_length'].min()

-1.8637802962695176

In [9]:
df['sepal_length'].max()

2.4836985805578657

In [10]:
import numpy as np

df['sepal_width'] = df['sepal_width'].apply(lambda x: np.log(x) if x != 0 else 0)

In [11]:
vmax = 10000
vmin = 10

df['petal_length'] = df['petal_length'].apply(lambda x: vmax if x > vmax else vmin if x < vmin else x)

In [12]:
import pandas as pd
df = pd.read_csv('/content/IRIS.csv')
df.dropna(axis=1,inplace=True)
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [13]:
import numpy as np
from sklearn.preprocessing import MaxAbsScaler

X = np.array(df['petal_length']).reshape(-1,1)
scaler = MaxAbsScaler()

In [14]:
scaler.fit(X)
X_scaled = scaler.transform(X)
df['sepal_width	'] = X_scaled.reshape(1,-1)[0]
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_width\t
0,5.1,3.5,1.4,0.2,Iris-setosa,0.202899
1,4.9,3.0,1.4,0.2,Iris-setosa,0.202899
2,4.7,3.2,1.3,0.2,Iris-setosa,0.188406
3,4.6,3.1,1.5,0.2,Iris-setosa,0.217391
4,5.0,3.6,1.4,0.2,Iris-setosa,0.202899

In [15]:
scaler.inverse_transform(X_scaled)

array([[1.4],
       [1.4],
       [1.3],
       [1.5],
       [1.4],
       [1.7],
       [1.4],
       [1.5],
       [1.4],
       [1.5],
       [1.5],
       [1.6],
       [1.4],
       [1.1],
       [1.2],
       [1.5],
       [1.3],
       [1.4],
       [1.7],
       [1.5],
       [1.7],
       [1.5],
       [1. ],
       [1.7],
       [1.9],
       [1.6],
       [1.6],
       [1.5],
       [1.4],
       [1.6],
       [1.6],
       [1.5],
       [1.5],
       [1.4],
       [1.5],
       [1.2],
       [1.3],
       [1.5],
       [1.3],
       [1.5],
       [1.3],
       [1.3],
       [1.3],
       [1.6],
       [1.9],
       [1.4],
       [1.6],
       [1.4],
       [1.5],
       [1.4],
       [4.7],
       [4.5],
       [4.9],
       [4. ],
       [4.6],
       [4.5],
       [4.7],
       [3.3],
       [4.6],
       [3.9],
       [3.5],
       [4.2],
       [4. ],
       [4.7],
       [3.6],
       [4.4],
       [4.5],
       [4.1],
       [4.5],
       [3.9],
       [4.8],
       [4. ],
       [4.9],
       [4.7],
       [4.3],
       [4.4],
       [4.8],
       [5. ],
       [4.5],
       [3.5],
       [3.8],
       [3.7],
       [3.9],
       [5.1],
       [4.5],
       [4.5],
       [4.7],
       [4.4],
       [4.1],
       [4. ],
       [4.4],
       [4.6],
       [4. ],
       [3.3],
       [4.2],
       [4.2],
       [4.2],
       [4.3],
       [3. ],
       [4.1],
       [6. ],
       [5.1],
       [5.9],
       [5.6],
       [5.8],
       [6.6],
       [4.5],
       [6.3],
       [5.8],
       [6.1],
       [5.1],
       [5.3],
       [5.5],
       [5. ],
       [5.1],
       [5.3],
       [5.5],
       [6.7],
       [6.9],
       [5. ],
       [5.7],
       [4.9],
       [6.7],
       [4.9],
       [5.7],
       [6. ],
       [4.8],
       [4.9],
       [5.6],
       [5.8],
       [6.1],
       [6.4],
       [5.6],
       [5.1],
       [5.6],
       [6.1],
       [5.6],
       [5.5],
       [4.8],
       [5.4],
       [5.6],
       [5.1],
       [5.1],
       [5.9],
       [5.7],
       [5.2],
       [5. ],
       [5.2],
       [5.4],
       [5.1]])

In [16]:
from sklearn.preprocessing import MinMaxScaler
X = np.array(df['petal_length']).reshape(-1,1)
scaler = MinMaxScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)
df['min max'] = X_scaled.reshape(1,-1)[0]
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_width\t,min max
0,5.1,3.5,1.4,0.2,Iris-setosa,0.202899,0.067797
1,4.9,3.0,1.4,0.2,Iris-setosa,0.202899,0.067797
2,4.7,3.2,1.3,0.2,Iris-setosa,0.188406,0.050847
3,4.6,3.1,1.5,0.2,Iris-setosa,0.217391,0.084746
4,5.0,3.6,1.4,0.2,Iris-setosa,0.202899,0.067797

In [18]:
from sklearn.preprocessing import StandardScaler

X = np.array(df['petal_length']).reshape(-1,1)
scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)
df['z score'] = X_scaled.reshape(1,-1)[0]
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_width\t,min max,z score
0,5.1,3.5,1.4,0.2,Iris-setosa,0.202899,0.067797,-1.341272
1,4.9,3.0,1.4,0.2,Iris-setosa,0.202899,0.067797,-1.341272
2,4.7,3.2,1.3,0.2,Iris-setosa,0.188406,0.050847,-1.398138
3,4.6,3.1,1.5,0.2,Iris-setosa,0.217391,0.084746,-1.284407
4,5.0,3.6,1.4,0.2,Iris-setosa,0.202899,0.067797,-1.341272